Support older Python 2.7 versions
Python 2.7.2 and 2.7.3 struct.unpack() fail with:

    error: unpack requires a string argument of length 4

Due to bytearray parameter. Casting as bytes() works for both Python 2.7.x and 3.x.

http://stackoverflow.com/questions/20612587/struct-unpack-with-bytearrays has more information